package model;

public enum ViewType {
    LOGIN,
    CHAT,
    CREATE_ACCOUNT,
    VIEW_ACCOUNT,
    ADMIN,
    PACIENT,
    VIEW_FACTURI,
    VIEW_PROGRAMARI_DOCTOR,
    VIEW_FISA_MEDICALA_PACIENT_DOCTOR,
    VIEW_DATE_PERSONALE_PACIENT_DOC,
}
